spring.application.name=project-backend-team-my-codebase-brings-all-the-boys
spring.profiles.active=dev

# Database configuration (PostgreSQL)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Hibernate configuration
spring.jpa.properties.hibernate.format_sql=true

spring.profiles.active=dev
