spring.application.name=project-backend-team-my-codebase-brings-all-the-boys
spring.profiles.active=dev

# Database configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/school_portal_db
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Hibernate configuration
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Ensure data.sql runs AFTER Hibernate creates the tables
spring.jpa.defer-datasource-initialization=true
# Security
spring.security.user.name=admin
spring.security.user.password=admin
# S3 configuration (Dummy values, replace with your own once AWS is set up, with .env, e.g. ${AWS_S3_BUCKET_NAME})
aws.s3.bucket-name=my-bucket-name