spring.application.name=project-backend-team-my-codebase-brings-all-the-boys

# Database configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/school_portal_db
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Security
# spring.security.user.name=admin
# spring.security.user.password=admin
